[package]
name = "alexa-record-selector"
version = "0.1.0"
authors = ["Trent Johnson <mr.trent.johnson@gmail.com>"]

[dependencies]
alexa_sdk = "^0.1"
lambda_runtime = "^0.1"
csv = "^1.1"
rand = "^0.7"
serde = { version = "^1.0", features = ["derive"]}